initial_positions:
  shoulder_pan_joint: 0.0
  shoulder_lift_joint: -2.39
  elbow_joint: 2.4
  wrist_1_joint: -3.15
  wrist_2_joint: -1.58
  wrist_3_joint: 3.15

# initial_positions:
#   shoulder_pan_joint: 1.57
#   shoulder_lift_joint: -2.43
#   elbow_joint: 2.10
#   wrist_1_joint: -2.81
#   wrist_2_joint: -1.56
#   wrist_3_joint: 3.15
# #