controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4

gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - eef_joint_l
    - eef_joint_r
