# controller_manager:
#   ros__parameters:
#     update_rate: 1000 #1500  # Hz 1500
#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# # parameters for each controller listed under controller manager
# arm_controller:
#   ros__parameters:
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     joints:
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - ee_joint_r
#       # - ee_joint_l
      
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.0
#       goal_time: 0.0

# joint_state_broadcaster:
#   ros__parameters:
#     type: joint_state_broadcaster/JointStateBroadcaster


# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_group_controller:
  ros__parameters:
    joints:
      - eef_joint_l
      - eef_joint_r
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity