controller_manager:
  ros__parameters:
    update_rate: 1000 #1500  # Hz 1500
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# parameters for each controller listed under controller manager
arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - eef_joint_l
      - eef_joint_r
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# joint_state_broadcaster:
#   ros__parameters:
#     type: joint_state_broadcaster/JointStateBroadcaster
